name: Deploy to Amazon ECS

on:
  workflow_dispatch:
    inputs:
      setRegion:
        description: 'Set region to deploy:'     
        required: true
        default: 'us-east-1' 
        type: choice
        options:
        - us-east-1
        - us-east-2
      setEnvironment:
        description: 'Set environment to deploy:'     
        required: true
        default: 'dev' 
        type: choice
        options:
        - prd
        - dev
        - stg  
      appName:
        description: 'Application name:'
        required: true
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ github.event.inputs.setRegion }}                                                      # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: dexco/${{ github.event.inputs.appName }}                                              # set this to your Amazon ECR repository name
  ECS_SERVICE: ${{ github.event.inputs.appName }}-service-${{ github.event.inputs.setEnvironment }}     # set this to your Amazon ECS service name
  ECS_CLUSTER: template-ecs-cluster                                                                     # set this to your Amazon ECS cluster name

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        cd ./app
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg config_env=${{ github.event.inputs.setEnvironment }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    #- name: Fill in the Amazon ECS task definition
    #  run: |
    #    echo "ECS_TASK_DEFINITION=$(aws ecs list-task-definitions --family-prefix ${{ github.event.inputs.appName }} --sort DESC --max-items 1 | grep arn | tr -d "\"" | tr -d " ")" >> $GITHUB_ENV
      - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ github.event.inputs.appName }} --query taskDefinition > task-definition.json
        
    #- name: Deploy Amazon ECS task definition
    #  run: |
    #    echo "${{ env.ECS_TASK_DEFINITION }}"
    #    aws ecs update-service --region ${{ github.event.inputs.setRegion }} --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ env.ECS_TASK_DEFINITION }} --force-new-deployment
      name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ github.event.inputs.appName }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true